### ISSUE TITLE
Botão de produtos da Home ultrapassando o limite

### ISSUE THREAD

**Issue by AnaNunes** [1carimflex/carimflex-style#28]
O botão dos produtos da home está ultrapassando a caixa onde se encontra o produto, assim como segue a imagem:

![screenshot_5](https://cloud.githubusercontent.com/assets/11012314/10585499/3cfb6070-7676-11e5-98a1-712467ebc943.png)

**Comment by jonyw4** [comment]
Esse problema não é referente a esse repositório.
