### ISSUE TITLE
Erro no filtro

### ISSUE THREAD

**Issue by AnaNunes** [1carimflex/carimflex-style#29]
Na página das máquinas é apresentada as seguintes informações no filtro:
![quantidade](https://cloud.githubusercontent.com/assets/11012314/10586423/d4ebdde8-767a-11e5-9d2f-a20e01875c40.png)

Quando na verdade o correto seria:
1 cromado
1 rosa
6 azuis

Além disso, na pagina de carimbos tradicionais, quando utilizo o filtro rosa, é apresentado carimbos preto e branco 

![rosa](https://cloud.githubusercontent.com/assets/11012314/10586548/77677ad2-767b-11e5-9816-62a4484187ab.png)

Assim como no filtro amarelo é apresentado um carimbo azul (neste caso pode ser um erro na foto também):

![amarelo](https://cloud.githubusercontent.com/assets/11012314/10586627/c6f8cf24-767b-11e5-91c8-75e17bd0d46d.png)

**Comment by jonyw4** [comment]
Esse problema não é referente a esse repositório.
