### ISSUE TITLE
Erro no frete ao retornar

### ISSUE THREAD

**Issue by AnaNunes** [1carimflex/carimflex-style#30]
Após realizar um pedido, ao clicar na opção "Alterar o carrinho" o campo de calcular frete desaparece assim como apresentado na imagem:
![calcular frete](https://cloud.githubusercontent.com/assets/11012314/10586927/7c200ea2-767d-11e5-9a89-b9e57818bb80.png)

**Comment by jonyw4** [comment]
Esse problema não é referente a esse repositório.
